# Generated by Django 3.2.19 on 2024-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combinaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elemento1', models.CharField(max_length=255)),
                ('elemento2', models.CharField(max_length=255)),
                ('resultado', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes/elementos/')),
            ],
            options={
                'db_table': 'combinaciones',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prueba',
            },
        ),
    ]
