# Generated by Django 3.2.19 on 2024-03-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleAIlchemy', '0002_alter_combinaciones_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinaciones',
            options={'verbose_name': 'Combinación', 'verbose_name_plural': 'Combinaciones'},
        ),
    ]
