# Generated by Django 3.2.19 on 2024-04-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleAIlchemy', '0003_alter_combinaciones_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Combinaciones',
            new_name='dbCombinaciones',
        ),
        migrations.RenameModel(
            old_name='Prueba',
            new_name='dbElementos',
        ),
        migrations.AlterModelTable(
            name='dbelementos',
            table='elementos',
        ),
    ]
