# Generated by Django 5.0.4 on 2024-04-24 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleAIlchemy', '0006_dbelementos_upload_alter_dbelementos_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dbelementos',
            name='creadores',
            field=models.ManyToManyField(related_name='elementosCreados', to=settings.AUTH_USER_MODEL),
        ),
    ]
