# Generated by Django 5.0.4 on 2024-05-02 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleAIlchemy', '0008_dbelementos_descubiertopor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcombinaciones',
            name='creadoresC',
            field=models.ManyToManyField(related_name='combinacionesCreados', to=settings.AUTH_USER_MODEL),
        ),
    ]
