# Generated by Django 5.0.4 on 2024-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleAIlchemy', '0009_dbcombinaciones_creadoresc'),
    ]

    operations = [
        migrations.CreateModel(
            name='victorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('victorias', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Victoria',
                'verbose_name_plural': 'Victorias',
                'db_table': 'victorias',
            },
        ),
    ]
